# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blogs
email: jansen.goyena@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jansengoyena.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
disqus:
    shortname: https-www-jansengoyena-xyz
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name             : "Jansen S. Goyena"
  avatar           : "/assets/img/profile_picture.jpg"
  bio              : "Works at Novare Technologies as an Associate Software Engineer. Jansen loves to Adventure and travel around the world. but don't have money. He Love and Fears God"
  location         : "Camarines Sur, Philippines"
  email            : "jansen.goyena@yahoo.com"
  website_url      : "https://www.jansengoyena.xyz"
  facebook         : "https://www.facebook.com/jansen.goyena"
  github           : "https://github.com/jansen07"